menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/ooatuoo
    GitHub: https://github.com/atuooo
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo: ooatuoo

# Analytics
# google-analytics:
ga: UA-67913126-2

# Copyright Infomation
startyear: 2016
